services:
  db:
    image: postgres:16
    container_name: shpe-uwm-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - shpe_uwm_db_data:/var/lib/postgresql/data

volumes:
  shpe_uwm_db_data:
