services:
  db:
    image: postgres:18
    container_name: romantic_davinci
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - a8d0013046272e2511e27440c1d59388d8aa570db2064f07dd1c576c8fa3a863:/var/lib/postgresql/data

volumes:
  a8d0013046272e2511e27440c1d59388d8aa570db2064f07dd1c576c8fa3a863:
